### ISSUE TITLE
Information about Team 4 Project

### ISSUE THREAD

**Issue by nimaka-BootCamp** [nimaka-BootCamp/IT-115-Group-Project-Team-4-Assignment-5#1]
As a contributor 
I need to know a bout the project
as a team 
we need to establish task and meeting schedule
then we can contribute to this project 

- [x] Modify Readme file
- [ ] Create contributing file
- [ ] Create road map file

**Comment by nimaka-BootCamp** [comment]
- [ ] Modify Readme file
- [ ] Create contributing file
- [ ] Create road map file

**Comment by OlenaNSC** [comment]
FGEIEDWED

**Comment by OlenaNSC** [comment]
the Sprint 1 - IT115 Team 4 Project
 Sprint Backlog

Olena, Аa а Head of Market Research, 
Needs to:
-to determine the project goals;
-check consumer demand for the Wiki page;
-introduced to teammates  the project;
- to check grammar and international ethics content;
So then contributors will know how to work on the project effectively, including the code of conduct.

Even, As a Project manager/Dev 
Needs to:
-to establish a task and meeting schedule;
-introduce a ROADMAP for Sprint 1;
-to determine the priority of tasks and assign them to team members;
-use the backlog to keep track of tasks that need to be completed in the future.
So then it should outline the future development of the project and provide a high-level view of upcoming features, enhancements, and milestones.

As a contributor, Jasper, As a software engineer/Lead Dev
Needs to:
- create a README file, a CONTRIBUTING file, 
-add a section for the GitHubWiki Page
- update the Wiki page with the progress made during Sprint 1.
-bring up any challenges faced, solutions implemented, and achievements unlocked;
-update the status of each task on the Kanban desk.
-be sure that the GitHub Wiki page correctly functions for mobile applications as well as for full-fledged sites;
- to check grammar and international ethics content;

As a contributor, Justin-UITX/De
Needs to:
-be sure that the GitHub Wiki page correctly functions for mobile applications as well as for full-fledged sites;
- to check grammar and international ethics content; 
- ensure that the acceptance criteria are clear, measurable, and aligned with the project's goals;
- offer feedback on the usability, functionality, and overall quality of the delivered features.
So then in this way, the Wiki page will be monetized.


As a Contributor, Nima-Lead/Product tester
-collaborate with the team to define test scenarios and acceptance criteria; 
 -develop comprehensive test plans that outline the testing approach, scope, and resources;
-conduct thorough testing of the implemented features and functionalities;
  -report any identified defects or issues
-maintain and update testing documentation, including test plans, test cases, and test results.
So then the HitHub Wiki Draft can be moved to " In Review".

As a Contributors
we need:
-coordinate with the Software Engineer/Lead Dev (Jasper), UITX/Dev (Justin), and Head of Market Research (Olena) to align testing activities with development and user feedback.

So then will contribute to ensuring the quality and reliability supporting the overall success of the IT115 Team 4 Project.

**Comment by OlenaNSC** [comment]
I based on roles

Evan- Project manger/Dev 
Jasper-software engineer/Lead Dev
Justin-UITX/Dev
Nima-Lead/Product tester
Olena-Head of market research
